import React, { ReactNode } from 'react'
import StreamVideoProvider from '../../../providers/StreamClientProvider'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Xooom",
  description: "Generated by Shivraj Soni | Video Call App | Next Gen Video Calling and Streaming App ",
  icons:{
    icon:'/icons/logo.svg'
  }
};
const RootLayout = ({children}:{children:ReactNode}) => {
  return (
    <main>
      <StreamVideoProvider>
        {children} 
      </StreamVideoProvider>
    </main>
  )
}

export default RootLayout
