import SideBar from '@/components/SideBar'
import Navbar from '@/components/Navbar'
import React, { ReactNode } from 'react'
import Footer from '@/components/Footer'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Xooom",
  description: "Generated by Shivraj Soni | Video Call App | Next Gen Video Calling and Streaming App ",
  icons:{
    icon:'/icons/logo.svg'
  }
};
const Homelayout = ({children}:{children:ReactNode}) => {
  return (
    <main className='relative'>
        <Navbar/> 
        <div className='flex'>
            <SideBar/> 
            <section className='flex min-h-screen flex-1 flex-col px-6 pb-6 pt-28 max-md:pb-14 sm:px-14'>
                <div className='w-full'>
                    {children}
                </div>
            </section>
            <Footer/>
        </div>
    </main>
  )
}

export default Homelayout
