import type { Metadata } from "next";
import "./globals.css";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const inter  = Inter({subsets:['latin']});

export const metadata: Metadata = {
  title: "Xooom",
  description: "Generated by Shivraj Soni | Video Call App | Next Gen Video Calling and Streaming App ",
  icons:{
    icon:'/icons/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#161925]`} // bg-dark-2
        >
          <ClerkProvider appearance={{
            layout:{
              logoImageUrl:'/icons/xoom-logo.svg',
              socialButtonsVariant:'iconButton'
            },
            variables:{
              colorText:'#fff',
              colorPrimary:'#0E78F9',
              colorBackground:'#1c1f2e',
              colorInputBackground:'#252a41',
              colorInputText:'#fff',

            }
          }}>
            {children}
            <Toaster/>
          </ClerkProvider>
      </body>
    </html>
  );
}
